---

resources: resources.yaml
samples: samples.tsv
units: units.tsv

default_container: "docker://hydragenetics/common:0.1.8"

exomedepth:
  ED_common: ""
  WW25: ""
  bedfile: ""
  conifer: ""
  container: ""
  reference_count: ""

manta_config_n:
  container: "docker://hydragenetics/manta:1.6.0"
  extra: ""

manta_run_workflow_n:
  container: "docker://hydragenetics/manta:1.6.0"

pindel_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

tiddit:
  container: "shub://J35P312/TIDDIT:latest"
