---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

exomedepth:
  container: ""
  bedfile: ""
  reference_count: ""

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"
