---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

expansionhunter:
    container: "docker://hydragenetics/expansionhunter:5.0.0"

exomedepth:
  bedfile: ""
  conifer: ""
  container: ""
  ED_common: ""
  reference_count: ""
  WW25: ""

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"
