---
resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.8"

cnvpytor_filter:
  container: "docker://hydragenetics/cnvpytor:1.2.1"
  dG_range: ""
  p_range: ""
  pN_range: ""
  Q0_range: ""
  view: ""

cnvpytor_readdepth:
  container: "docker://hydragenetics/cnvpytor:1.2.1"
  length_list: ""

exomedepth:
  ED_common: ""
  WW25: ""
  bedfile: ""
  conifer: ""
  container: "docker://hydragenetics/exomedepth:1.1.15"
  reference_count: ""

expansionhunter:
  container: "docker://hydragenetics/expansionhunter:5.0.0"

manta_config_n:
  container: "docker://hydragenetics/manta:1.6.0"
  extra: ""

manta_run_workflow_n:
  container: "docker://hydragenetics/manta:1.6.0"

pindel_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

tiddit:
  container: "docker://hydragenetics/tiddit:3.3.2"
